---
- name: Configure server
  hosts: all
  become: true

  vars_files:
    - applications.yml

  roles:
    - role: common
      tags:
        - common

    - role: users
      tags:
        - users

    - role: docker
      tags:
        - docker

    - role: firewall
      tags:
        - firewall

    - role: traefik
      tags:
        - traefik

    - role: applications
      tags:
        - applications
